### ISSUE TITLE
[报表]添加报表规则过滤选项中选择了列、页面不显示列的名

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#102]
添加报表规则过滤选项中选择了列、页面不显示列的名

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180107_3125_x64.exe  版本确认，close处理。

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180112_3150_x64.exe 版本确认，又出现此现象

![default](https://user-images.githubusercontent.com/28615156/34928521-13071486-f9f9-11e7-98f4-e7ff65ee065a.png)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180207_3249_x64.exe  版本确认，close处理。
