### ISSUE TITLE
[管理]合同页面、删除合同信息跳转页面空白显示

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#105]
1.合同页面、删除合同信息跳转页面空白显示
2.管理类型中分类菜单中删除都有这个问题

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
![default](https://user-images.githubusercontent.com/28615156/34656668-4edd3766-f458-11e7-894a-a31781f235b7.png)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180107_3125_x64.exe  版本确认，close处理。
