### ISSUE TITLE
[资产管理]资产查询页面、在查询窗中多了必选项的“*”

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#109]
1.资产查询页面、在查询窗中多了必选项的“*”

![default](https://user-images.githubusercontent.com/28615156/34661386-51c66c28-f484-11e7-9548-54bbd4687e6e.png)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180112_3150_x64.exe 版本确认，close处理。
