### ISSUE TITLE
[资产备件]加一个能在资产备件进行资产申请功能

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/am#11]
[资产备件]加一个能在资产备件进行资产申请功能

![image](https://user-images.githubusercontent.com/22296563/29757044-777feb22-8bdb-11e7-9b4d-7ea687c1bc7d.png)

**Comment by runner-mei** [comment]
这个看不懂，什么意思？

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180107_3125_x64.exe  版本确认，close处理。
