### ISSUE TITLE
[备案管理]备案的统计报表中、配置项中出现资产的配置项

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#111]
1.备案的统计报表中、配置项中出现资产的配置项
2.添加配置配置项类型中的父类同样出现此现象

![default](https://user-images.githubusercontent.com/28615156/34663222-c1199292-f490-11e7-8386-90824ed2e49a.png)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180123_3203_x64.exe  版本确认，close处理。
