### ISSUE TITLE
[资产管理]资产管理下的CMDB配置项类型下、出现备案的配置项类型

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#112]
1.资产管理下的CMDB配置项类型下、出现备案的配置项类型

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
CMDB同样出现此现象
![default](https://user-images.githubusercontent.com/28615156/34976925-aacd59f8-fad3-11e7-902c-1e1d309b6a05.png)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180124_3206_x64.exe 版本确认，close处理。
