### ISSUE TITLE
[预警管理]添加预警管理、预警不生效、没有告警触发

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#115]
1.添加预警管理、预警不生效、没有告警触发

**Comment by hengwei-lhm** [comment]
我这里没问题 预警管理首页有个运维平台配置 看看是不是运维平台的端口与地址填写不正确

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180202_3234_x64.exe  版本确认，资产的预警没有触发

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180207_3249_x64.exe  版本确认，close处理。
