### ISSUE TITLE
[备案管理]资产添加的报表、在备案管理的报表中也显示

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#117]
资产添加的报表、在备案管理的报表中也显示

![default](https://user-images.githubusercontent.com/28615156/34929204-6f7be29c-f9fd-11e7-8921-af4038eb619d.png)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180124_3206_x64.exe 版本确认，新建报表规则无效

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180125_3208_x64.exe 版本确认，close处理。
