### ISSUE TITLE
[备案管理]备案管理端口扫描时、提示错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#118]
1.备案管理端口扫描时、提示错误

![default](https://user-images.githubusercontent.com/28615156/34929448-e91e5890-f9fe-11e7-8642-609c67bc1c40.png)

![default](https://user-images.githubusercontent.com/28615156/34929453-edc9bd94-f9fe-11e7-8360-7ea50dff693c.png)

**Comment by hengwei-lhm** [comment]
我这没问题 你看看是不是和上次一样 nmap打不开

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180123_3203_x64.exe  版本确认，close处理。
