### ISSUE TITLE
[打印标签]打印标签页面、点击添加打印对象无效

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#120]
1.打印标签页面、点击添加打印对象无效
![default](https://user-images.githubusercontent.com/28615156/34975610-9622e83e-facd-11e7-9d8e-541602251ad6.png)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180118_3172_x64.exe 版本确认，close处理。
