### ISSUE TITLE
[资产管理]首页点击设备类型跳转页面配置项为空

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#123]
1.首页点击设备类型跳转页面配置项为空
2.显示和隐藏按钮提示错误

![default](https://user-images.githubusercontent.com/28615156/35309645-7846bb80-00e8-11e8-8772-d2d8d7873001.png)

![default](https://user-images.githubusercontent.com/28615156/35309647-7b3d8ca6-00e8-11e8-9d2e-13ca33192d31.png)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180124_3206_x64.exe 版本确认，close处理。
