### ISSUE TITLE
[预警管理]添加预警规则提示错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#125]
添加预警规则提示错误

![default](https://user-images.githubusercontent.com/28615156/35369048-23c07e3c-01c1-11e8-90b9-a033013b5428.png)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180202_3234_x64.exe  版本确认，close处理。
