### ISSUE TITLE
[资产]资产编辑页面、点击影响度的添加按钮无效

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#126]
1.资产编辑页面、点击影响度的添加按钮无效
2.地点、供应商等同样出现此现象

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180125_3210_x64.exe 版本确认，还出现此现象

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180202_3234_x64.exe  版本确认，close处理。
