### ISSUE TITLE
[资产管理]从平台同步过来的数据、编辑中选择被监控后、点击确定提示错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#127]
1.从平台同步过来的数据、编辑中选择被监控后、点击确定提示错误

![default](https://user-images.githubusercontent.com/28615156/35370921-d21faef8-01cb-11e8-821f-52879a3af699.png)

![default](https://user-images.githubusercontent.com/28615156/35370900-b8efbe96-01cb-11e8-88cb-8a414662b9a7.png)

**Comment by hengwei-lhm** [comment]
你看下你的资产状态是不是空的

**Comment by hengwei-test** [comment]
没有资产状态

![default](https://user-images.githubusercontent.com/28615156/35422089-d1c3e9fe-0281-11e8-838a-0344fbd694d6.png)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180301_3300_x64.exe   版本确认，close处理。
