### ISSUE TITLE
[资产管理]添加报表规则成功后、在报表规则页面不显示

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#129]
1.添加报表规则成功后、在报表规则页面不显示

![default](https://user-images.githubusercontent.com/28615156/35372272-f22a9106-01d3-11e8-8978-7701a599c641.png)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180202_3234_x64.exe  版本确认，还是有itsm的cmdb


![default](https://user-images.githubusercontent.com/28615156/35789049-501e95de-0a74-11e8-839e-f3d95b8373a5.png)

**Comment by hengwei-lhm** [comment]
备案里只有备案的数据，资产里有除了备案的数据

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180207_3249_x64.exe  版本确认，close处理。
