### ISSUE TITLE
[资产管理]资产信息查看窗口、字体的大小与原先不符

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#132]
1.资产信息查看窗口、字体的大小与原先不符

![default](https://user-images.githubusercontent.com/28615156/35375821-5d9d7854-01e3-11e8-84d1-a8a79b573363.png)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180125_3210_x64.exe 版本确认，close处理。
