### ISSUE TITLE
[资产管理]CMDB页面、缩小菜单、左边的窗口没有自适应

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#133]
1.CMDB页面、缩小菜单、左边的窗口没有自适应

![1516946683 1](https://user-images.githubusercontent.com/28615156/35427022-f104c2fa-02a1-11e8-97f1-411f24cdf827.jpg)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180202_3234_x64.exe  版本确认，close处理。
