### ISSUE TITLE
[资产管理]在添加框架添加上一层信息时、页面首页、用户信息别显示

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#134]
1.在添加框架添加上一层信息时、页面首页、用户信息别显示

![default](https://user-images.githubusercontent.com/28615156/35490822-4283d64c-04dd-11e8-9f2b-1e64be994923.png)

![default](https://user-images.githubusercontent.com/28615156/35490830-4a0bd9b4-04dd-11e8-8050-6feffffc66c3.png)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180202_3234_x64.exe  版本确认，点击添加地点的确认按钮无效

![default](https://user-images.githubusercontent.com/28615156/35788513-7ba8a8ec-0a70-11e8-81a3-7ca568e105eb.png)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180207_3243_x64.exe  版本确认，还出现此现象

![default](https://user-images.githubusercontent.com/28615156/35896400-eeba679e-0bf6-11e8-9d0b-05a3ce216b9e.png)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180207_3249_x64.exe  版本确认，close处理。
