### ISSUE TITLE
[资产管理]添加的字段分组、点击编辑按钮提示错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#135]
1.添加的字段分组、点击编辑按钮提示错误

![default](https://user-images.githubusercontent.com/28615156/35491273-69ca8f22-04e0-11e8-940e-4f8aaf2db066.png)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180202_3234_x64.exe  版本确认，close处理。
