### ISSUE TITLE
[资产管理]首页在右上角的查询中、资产页面查询能够查询出来备案的信息

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#137]
1.首页在右上角的查询中、资产页面查询能够查询出来备案的信息

![1517194873 1](https://user-images.githubusercontent.com/28615156/35491813-e9a158b8-04e3-11e8-8aa2-2da44f52f01f.jpg)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180207_3243_x64.exe  版本确认，还是有次问题

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180207_3249_x64.exe  版本确认，close处理。
