### ISSUE TITLE
[资产管理]搜索结果页面、查询出来的数据、某些状态没有的时候信息显示为“<nil>”

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#138]
1.搜索结果页面、查询出来的数据、某些状态没有的时候信息显示为“nil”
2.把“nil”值修改成一个直观显示的值

![1517194873 1](https://user-images.githubusercontent.com/28615156/35491865-3154a3ea-04e4-11e8-84c8-dbea92b99585.jpg)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180202_3234_x64.exe  版本确认，close处理。
