### ISSUE TITLE
[备案管理]端口备案中默认字段未自动添加

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#140]
1.端口备案中默认字段未自动添加

![default](https://user-images.githubusercontent.com/28615156/35493945-0d2a1064-04f2-11e8-95bb-cac6bdce05bd.png)

![default](https://user-images.githubusercontent.com/28615156/35493948-12918c12-04f2-11e8-946d-8aefa9667ea1.png)

![default](https://user-images.githubusercontent.com/28615156/35494001-61c89fdc-04f2-11e8-8e07-6af5634f0080.png)

**Comment by hengwei-lhm** [comment]
端口备案的默认字段不再自动添加

**Comment by hengwei-lhm** [comment]
删除提示文言

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180202_3234_x64.exe  版本确认，close处理。
