### ISSUE TITLE
[资产管理]菜单中点击“IT资”、给一个默认的配置项

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#141]
1.菜单中点击“IT资”、给一个默认的配置项
2.非IT资产、资产组件同样出现此问题

![default](https://user-images.githubusercontent.com/28615156/35494838-570a0652-04f8-11e8-9f2f-9a114e02da1f.png)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180202_3234_x64.exe  版本确认，close处理。
