### ISSUE TITLE
[资产管理]搜索资产信息时、当未搜索到资产信息、给个未提示

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#142]
1.搜索资产信息时、当未搜索到资产信息、给个未提示
2.“未搜索到xxxxxx资产信息”

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180202_3234_x64.exe  版本确认，close处理。
