### ISSUE TITLE
[备案管理]端口扫描后、在导入端口备案映射字段时、添加一个添加默认信息的框

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#144]
1.端口扫描后、在导入端口备案映射字段时、添加一个添加默认信息的框

![1517804860 1](https://user-images.githubusercontent.com/28615156/35788467-1952e310-0a70-11e8-8ac4-ffab514e3d8b.jpg)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180301_3300_x64.exe   版本确认，close处理。
