### ISSUE TITLE
[资产管理]资产管理中右上角的当前用户使用“用户名”

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#145]
1.资产管理中右上角的当前用户使用“用户名”
2.备案同样出现此现象
3.修改成功 使用“中文名”

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180207_3243_x64.exe  版本确认，close处理。
