### ISSUE TITLE
[资产管理]导入资产更新数据时、一部分数据不更新

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#146]
1.导入资产更新数据时、一部分数据不更新
1.开始数据;
![1517822426 1](https://user-images.githubusercontent.com/28615156/35796874-eb57c47a-0a98-11e8-9ad8-6de0fd0fee63.jpg)

2.需要导入的数据：
![1517822381 1](https://user-images.githubusercontent.com/28615156/35796891-f4b26df4-0a98-11e8-9f4b-b4647aad8a8c.jpg)

3.导入后的数据：

![1517822554 1](https://user-images.githubusercontent.com/28615156/35796980-3a34afa4-0a99-11e8-9f48-fd551517dfa0.jpg)

**Comment by hengwei-lhm** [comment]
应该是 #147 这个bug导致的 修复后应该是没问题了 我测是正常的

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180207_3243_x64.exe  版本确认，close处理。
