### ISSUE TITLE
[资产管理]tpt_am进程一直在重启

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#148]
hengwei_setup_3.3.1.20180207_3249_x64.exe 版本的 tpt_am进程一直在重启

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180211_3262_x64.exe  版本确认，close处理。

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180211_3262_x64.exe  版本确认，close处理。
