### ISSUE TITLE
[资产管理]当预警规则的资产删除后、预警规则不能编辑、需要重新添加

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#149]
1.当预警规则的资产删除后、预警规则不能编辑、需要重新添加
2.当对个资产对应一条预警规则、其中一个资产删除导致规则不能用、这样的实现方式不方便
3.正确的方法：其中一个资产删除、规则对应的资产删除、告警规则可以继续使用

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180301_3300_x64.exe   版本确认，close处理。
