### ISSUE TITLE
[资产管理]在查询条件中的地点添加按钮删除

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#154]
1.在查询条件中的地点添加按钮删除

![default](https://user-images.githubusercontent.com/28615156/36013473-62ea32d0-0d9f-11e8-8b25-4483d193d632.png)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180211_3262_x64.exe  版本确认，close处理。
