### ISSUE TITLE
[资产管理]添加报表时、添加过滤项时、提示“500  Internal Server Error  {"error":"strconv.ParseInt: parsing \"1907\": value out of range"}”

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#156]
1.添加报表时、添加过滤项时、提示“500  Internal Server Error  {"error":"strconv.ParseInt: parsing \"1907\": value out of range"}”

![default](https://user-images.githubusercontent.com/28615156/36014009-8f3776ba-0da2-11e8-82e0-44891eebdcd0.png)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180211_3262_x64.exe  版本确认，close处理。
