### ISSUE TITLE
[资产管理]资产导入、选择csv导入、在选择配置字段时、页面的格式错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#160]
1.资产导入、选择csv导入、在选择配置字段时、页面的格式错误

![default](https://user-images.githubusercontent.com/28615156/36824449-4cab463c-1d3d-11e8-9f73-f10745c7fe6f.png)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180301_3300_x64.exe   版本确认，close处理。
