### ISSUE TITLE
[资产管理]合同页面、删除合同信息时、提示信息不对

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#162]
1.合同页面、删除合同信息时、提示信息不对

“remove data\asset_management\contracts: The directory is not empty.”

![default](https://user-images.githubusercontent.com/28615156/36828025-267fb9ba-1d52-11e8-8027-7960964c2fed.png)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180301_3300_x64.exe   版本确认，close处理。
