### ISSUE TITLE
[资产管理]编辑统计表报规则时、分组显示不选的情况下、点击修改按钮、修改后自动保存分组信息

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#165]
1.编辑统计表报规则时、分组显示不选的情况下、点击修改按钮、修改后自动保存分组信息

1.不保存分组信息：
![1519968231 1](https://user-images.githubusercontent.com/28615156/36884609-0247f21c-1e1d-11e8-8606-8f283a5c48e8.jpg)

2.编辑规则时、自动添加分组;
![1519968281 1](https://user-images.githubusercontent.com/28615156/36884633-1f242fea-1e1d-11e8-8d00-54a6d9abfea6.jpg)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180305_3311_x64.exe   版本确认，close处理。
