### ISSUE TITLE
[资产管理]添加申请页面，选择资产时、无法获取资产的数据

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#167]
1.添加申请页面，选择资产时、无法获取资产的数据

![1519970313 1](https://user-images.githubusercontent.com/28615156/36885463-07154506-1e22-11e8-8245-dbe25d2066a2.jpg)

资产数据：
![default](https://user-images.githubusercontent.com/28615156/36885469-13624c46-1e22-11e8-82f2-327f5db7c95b.png)

**Comment by hengwei-lhm** [comment]
只会显示 资产状态为默认状态的对象 （ storeapplicationconfig.json 中的 default 选项  ）
 资产启用( storeapplicationconfig.json 中的 use选项  ) 
 资产借出( storeapplicationconfig.json 中的 loan选项  )
