### ISSUE TITLE
[资产管理]CMDB中关系类型添加成功后、在关系类型页面不显示

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#168]
1.CMDB中关系类型添加成功后、在关系类型页面不显示

![1519971033 1](https://user-images.githubusercontent.com/28615156/36885718-a805e6a4-1e23-11e8-915e-af90f01f969a.jpg)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180305_3311_x64.exe   版本确认，还出现此现象

**Comment by hengwei-test** [comment]
1
