### ISSUE TITLE
[资产管理]IE兼容问题，资产管理中 图片中的一排按钮，点击没有反应

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/am#17]
[资产管理]IE兼容问题，资产管理中 图片中的一排按钮，点击没有反应
![image](https://user-images.githubusercontent.com/22296563/30047716-2d421d26-9245-11e7-830a-26668b0121d0.png)

**Comment by hengwei-wtk** [comment]
ok

**Comment by xiauye** [comment]
还是存在

**Comment by hengwei-wtk** [comment]
OK

**Comment by xiauye** [comment]
显示列设置没有起效
![image](https://user-images.githubusercontent.com/22296563/31592623-3f4b161c-b25c-11e7-8655-2efaafda4fe4.png)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20171115_2963_x64.exe  版本确认，close处理。
