### ISSUE TITLE
[资产管理]IE兼容问题，主菜单没有显示

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/am#18]
[资产管理]IE兼容问题，主菜单没有显示
![image](https://user-images.githubusercontent.com/22296563/30047767-700661e4-9245-11e7-91a7-1bf3c33e0b2d.png)

**Comment by hengwei-wtk** [comment]
ok

**Comment by xiauye** [comment]
还是存在

**Comment by xiauye** [comment]
已验证
