### ISSUE TITLE
[资产管理] IE兼容问题 ， 每一个资产没有线条分格 

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/am#19]
[资产管理] IE兼容问题 ， 每一个资产没有线条分格 
![image](https://user-images.githubusercontent.com/22296563/30047821-b5303f2e-9245-11e7-896a-6da48e6cf9cc.png)

**Comment by hengwei-wtk** [comment]
ok

**Comment by xiauye** [comment]
ok
