### ISSUE TITLE
[资产管理]导入资产，新建的CMDB分组，没有任何数据，没有默认覆盖原数据并导入字段

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/am#20]
[资产管理]导入资产，新建的CMDB分组，没有任何数据，没有默认覆盖原数据并导入字段

![image](https://user-images.githubusercontent.com/22296563/30047854-efe51130-9245-11e7-88c9-1f3f897f8a94.png)

**Comment by hengwei-wtk** [comment]
已修复

**Comment by xiauye** [comment]
ok
