### ISSUE TITLE
[资产管理]查看资产信息内外边框的显示问题

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/am#21]
[资产管理]查看资产信息内外边框的显示问题

![image](https://user-images.githubusercontent.com/22296563/30048131-4efaea22-9247-11e7-9cbb-513b1fd85816.png)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by xiauye** [comment]
显示列多了，操作列表就挤压过去了
![image](https://user-images.githubusercontent.com/22296563/31593701-cf40121c-b262-11e7-8e1f-1d775b58c437.png)

**Comment by hengwei-lhm** [comment]
这控件的列宽计算方式分为两种，一种是自动计算，一种是自定义列宽，这种情况只能使用自动计算列宽，目前只能靠拖动来缩放列宽
