### ISSUE TITLE
[资产管理]库房管理可以自定义多个库房。

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/am#22]
[资产管理]库房管理可以自定义多个库房。

可以这么理解：一个大公司，有很多个分公司，那么就会有多个库房。

**Comment by hengwei-lhm** [comment]
可以在 自定义字段中加一个枚举字段

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180116_3158_x64.exe  版本确认，close处理。
