### ISSUE TITLE
[资产管理]例如：审计，选择一个记录删除，分页将被隐藏。

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/am#27]
[资产管理]例如：审计，选择一个记录删除，分页将被隐藏。 其他页面分页也是一样。
![image](https://user-images.githubusercontent.com/22296563/30048352-596d106a-9248-11e7-8115-a5a6e64b39c5.png)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by xiauye** [comment]
已验证
