### ISSUE TITLE
[资产管理]IE兼容，配置项类型

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/am#28]
[资产管理]IE兼容，配置项类型
![image](https://user-images.githubusercontent.com/22296563/30048416-a0ac125a-9248-11e7-9360-93da4ea51d81.png)

**Comment by hengwei-wtk** [comment]
ok

**Comment by xiauye** [comment]
还是存在

**Comment by hengwei-wtk** [comment]
已修复

**Comment by xiauye** [comment]
已确认
