### ISSUE TITLE
[资产管理]例如：合同，选择有效时期可以准确的实现手动输入

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/am#29]
[资产管理]例如：合同，选择有效时期可以准确的实现手动输入
![image](https://user-images.githubusercontent.com/22296563/30048522-28e37a6e-9249-11e7-8468-861f2be4a2a5.png)

**Comment by hengwei-lhm** [comment]
输入正确值时没问题，输入错误值时 例如:2017/10/35 会自动纠正为 2017/11/04
