### ISSUE TITLE
[资产未归还提前通知]没有把资产的ID号发过来

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/am#30]
[资产未归还提前通知]没有把资产的ID号发过来
![image](https://user-images.githubusercontent.com/22296563/30099485-6622b30c-9318-11e7-94e0-17aa7dcab29d.png)

**Comment by hengwei-lhm** [comment]
fixed 可以自己定义告警模版

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180207_3249_x64.exe  版本确认，close处理。
