### ISSUE TITLE
[自定义生成报表]查看版本直接报错

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/am#31]
[自定义生成报表]查看版本直接报错
![image](https://user-images.githubusercontent.com/22296563/30105253-a457d3ca-932a-11e7-902f-40bde566a4d1.png)

**Comment by hengwei-wtk** [comment]
ok

**Comment by xiauye** [comment]
还是报错

**Comment by hengwei-lhm** [comment]
fixed
