### ISSUE TITLE
[资产一览]没有全部把资产显示出来

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/am#32]
[资产一览]没有全部把资产显示出来

![image](https://user-images.githubusercontent.com/22296563/30143255-7733fdf0-93b7-11e7-8c89-646c3f4c8c89.png)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by xiauye** [comment]
点击其它也没有展现出来。 对于多余的资产类型可以做一个滚动条
