### ISSUE TITLE
[报表规则管理】设置资产报表规则，在运维平台中报表规则管理，直接报错

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/am#40]
[报表规则管理】设置资产报表规则，在运维平台中报表规则管理，直接报错
![image](https://user-images.githubusercontent.com/22296563/30574519-12ffbebc-9d2d-11e7-84e1-6524299b527a.png)

**Comment by hengwei-wtk** [comment]
ok

**Comment by xiauye** [comment]
报错还是存在

**Comment by hengwei-wtk** [comment]
更新运维平台中的配置

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180123_3203_x64.exe  版本确认，close处理。
