### ISSUE TITLE
[菜单]例如管理菜单将菜单展开，点击其中的一项就会缩回去。

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/am#44]
[菜单]例如管理菜单将菜单展开，点击其中的一项就会缩回去。（管理。软件）两大菜单
![image](https://user-images.githubusercontent.com/22296563/31535400-99954ba0-b02d-11e7-92b4-cd935ac436fd.png)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by xiauye** [comment]
已验证
