### ISSUE TITLE
[资产查看]直接报错

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/am#46]
[资产查看]直接报错
![image](https://user-images.githubusercontent.com/22296563/31540405-2965da82-b03e-11e7-96cc-b332535ddcaa.png)

**Comment by hengwei-wtk** [comment]
关系表数据库没有创建 现已创建好了

**Comment by xiauye** [comment]
还是报错

**Comment by hengwei-wtk** [comment]
现在已经修复了

**Comment by xiauye** [comment]
已确认
