### ISSUE TITLE
[CMDB]没有选中配置项目，点击添加，没有任何提示。

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/am#49]
[CMDB]没有选中配置项目，点击添加，没有任何提示。
![image](https://user-images.githubusercontent.com/22296563/31599168-b87639d2-b283-11e7-817d-24ac211a08c3.png)

**Comment by hengwei-wtk** [comment]
提示已添加

**Comment by hengwei-test** [comment]
已经确认，close处理
