### ISSUE TITLE
[资产一览] 点击任意一个分组可以查看字段的详细信息。或者跳到属点击的资产页面中

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/am#5]
[资产一览] 点击任意一个分组可以查看字段的详细信息。或者跳到属点击的资产页面中
![image](https://user-images.githubusercontent.com/22296563/29702662-c68c0d42-89a4-11e7-933a-063101fd7af8.png)

**Comment by hengwei-wtk** [comment]
已添加

**Comment by xiauye** [comment]
ok
