### ISSUE TITLE
[报表]资产统计出来的报表不规则

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/am#50]
[报表]资产统计出来的报表不规则
![image](https://user-images.githubusercontent.com/22296563/31605482-e5541b62-b298-11e7-963f-f8e222296d5c.png)

**Comment by hengwei-wtk** [comment]
已修复

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20171107_2927_x64.exe  版本确认、还是有问题。

![1510133855 1](https://user-images.githubusercontent.com/28615156/32541762-ae8304d4-c4ab-11e7-9453-b9898e494c21.jpg)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
![default](https://user-images.githubusercontent.com/28615156/34371818-4d49384c-eb0b-11e7-9f84-65120c8fce0d.png)

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180107_3125_x64.exe  版本确认，close处理。
