### ISSUE TITLE
[资产添加]添加资产页面，添加的信息是必选项时，在添加项目的名称前面添加一个“*”符号

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#59]
1.添加资产页面，添加的信息是必选项时，在添加项目的名称前面添加一个“*”符号

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
还是没有图标显示
![default](https://user-images.githubusercontent.com/28615156/34657248-56dd003e-f45f-11e7-939e-7f5862395113.png)

![default](https://user-images.githubusercontent.com/28615156/34657270-6e8c176a-f45f-11e7-8f28-873882c76ba1.png)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180107_3125_x64.exe  版本确认，close处理。
