### ISSUE TITLE
[资产管理]资产管理页面、显示列设置窗口信息显示不全

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#65]
1.资产管理页面、显示列设置窗口信息显示不全

![1510121839 1](https://user-images.githubusercontent.com/28615156/32534385-46f92728-c490-11e7-869d-77b2a23df026.jpg)

**Comment by hengwei-lhm** [comment]
fixed 数据库结构问题 下次更新后 会自动更新数据库结构

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20171115_2963_x64.exe  版本确认，close处理。
