### ISSUE TITLE
[软件]删除许可协议时、提示“remove data\asset_management\license_agreements: The directory is not empty.”

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#69]
1.删除许可协议时、提示“remove data\asset_management\license_agreements: The directory is not empty.”

![1510126952 1](https://user-images.githubusercontent.com/28615156/32536964-a5140bba-c49b-11e7-859d-e08bf6976b23.jpg)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20171115_2963_x64.exe  版本确认，close处理。
