### ISSUE TITLE
[配置项类型]添加配置项类型页面、缺省字段重叠显示

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#71]
1.添加配置项类型页面、缺省字段重叠显示

![1510130123 1](https://user-images.githubusercontent.com/28615156/32538960-e2e4ed86-c4a2-11e7-9edf-15dbeabbd0cc.jpg)

**Comment by hengwei-lhm** [comment]
fixed 再次出现请确认数据库中 tpt_meta_attribuates的label字段不为空

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20171115_2963_x64.exe  版本确认，close处理。
