### ISSUE TITLE
[资产管理]全局搜索资产时、未搜索到资产、菜单栏显示全部打开

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#74]
1.全局搜索资产时、未搜索到资产、菜单栏显示全部打开
2.菜单栏右边有填充颜色
3.当未搜索到设备时、添加提示信息:"未搜索到XXXXXXXX资产信息"

![1510133061 1](https://user-images.githubusercontent.com/28615156/32541241-04d6ec30-c4aa-11e7-82ee-e45c4470ea93.jpg)

**Comment by hengwei-lhm** [comment]
fixed
