### ISSUE TITLE
[IT资产管理]安装平台后am服务一直在重启

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#75]
1.安装平台后am服务一直在重启

2017/11/09 14:11:47 init.go:155: 更新资产数据失败update meta_fieldspq: 重复键违反唯一约束"tpt_meta_attributes_owner_id_name_key"
[assetmanagement][sys] wait process failed - exit status 4294967295
[assetmanagement][sys] --------------------  proc end  --------------------
[assetmanagement]2017-11-09 14:11:47.3378659 +0800 CST [sys]current status is 'SRV_RUNNING'
[assetmanagement][sys] -------------------- proc start --------------------
[assetmanagement][sys] C:\Program Files\hengwei/bin/tpt_am.exe
[assetmanagement][sys] 		-importPath
[assetmanagement][sys] 		assetmanagement
[assetmanagement][sys] 		-srcPath
[assetmanagement][sys] 		C:\Program Files\hengwei/lib
[assetmanagement][sys] 		-runMode
[assetmanagement][sys] 		prod
slugify: ->名称
slugify: ->描述
slugify: ->影响度
slugify: ->

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20171115_2963_x64.exe  版本确认，close处理。
