### ISSUE TITLE
[资产管理]主页上资产管理一览显示不全、没有滚动条

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#77]
1.主页上资产管理一览显示不全、没有滚动条

![1510897891 1](https://user-images.githubusercontent.com/28615156/32931312-83947e8e-cb9e-11e7-9be6-02c87b9a784d.jpg)

![1510897906 1](https://user-images.githubusercontent.com/28615156/32931313-83d493ca-cb9e-11e7-86c2-41ad902a8ade.jpg)

**Comment by hengwei-lhm** [comment]
fixed
