### ISSUE TITLE
[资产导入]导入数据中带“地点”“名称”“描述”“影响度”时、在导入页面显示的自定义字段中重复显示

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#79]
1.导入数据中带“地点”“名称”“描述”“影响度”是、在导入页面显示的自定义字段中重复显示

![1510907206 1](https://user-images.githubusercontent.com/28615156/32937683-76dc50f2-cbb4-11e7-8f8c-8b4df81471d5.jpg)

**Comment by hengwei-lhm** [comment]
fixed
