### ISSUE TITLE
[资产管理]入库的设备在库房有一个唯一的ID、打印标签的id、就是库房里的这个唯一id

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#86]
1.入库的设备在库房有一个唯一的ID、打印标签的id、就是库房里的这个唯一id

**Comment by hengwei-lhm** [comment]
可以在资产里配置自定义生成字段 在添加的时候 自动生成

**Comment by hengwei-lhm** [comment]
自定生成字段 在库房创建记录时 id为库房的序列号 如果是在资产或备案中创建时 id为配置项的序列号
