### ISSUE TITLE
[提示信息] 所有的提示信息不会自动消失

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/am#9]
[提示信息] 所有的提示信息不会自动消失，新增，删除，修改
       [添加权限]  报表的显示问题
![image](https://user-images.githubusercontent.com/22296563/29708215-876090d2-89ba-11e7-8a94-cb5a2ff3c2c1.png)

**Comment by hengwei-lhm** [comment]
有需求再改

**Comment by hengwei-lhm** [comment]
报表显示问题已修复
