### ISSUE TITLE
[审计]审计操作中详情显示唯一标识

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#95]
审计操作中详情显示唯一标识

![img_20180104_110759](https://user-images.githubusercontent.com/28615156/34565190-c5d2134e-f194-11e7-94b6-e821510e9a08.jpg)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180107_3125_x64.exe  版本确认，close处理。
