### ISSUE TITLE
[报表]生成报表规则的分组显示为空时、生成报表没有数据

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/am#99]
生成报表规则的分组显示为空时、生成报表没有数据

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
无法生成报表
![default](https://user-images.githubusercontent.com/28615156/34657153-7347cd18-f45e-11e7-9cf9-b325b4eb7595.png)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
没选择分组还是没法生成报表、  选择分组的报表规则生成表报没有数据

**Comment by hengwei-lhm** [comment]
fixed
